name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza todo dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # ========================
          # Configuração básica
          # ========================
          user: PedroFerreiraBento
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          # ========================
          # Plugins extras
          # ========================
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage

          plugin_stars: yes
          plugin_stars_limit: 4
