name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Topics + Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: m-topics-achievements.svg
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_topics_limit: 12
          plugin_achievements: yes
          plugin_achievements_display: detailed

      - name: Licenses + Recently Starred
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: m-licenses-stars.svg
          plugin_licenses: yes
          plugin_licenses_setup: permissions, limitations, conditions
          plugin_licenses_ratio: yes
          plugin_stars: yes
          plugin_stars_limit: 8

      - name: Languages (Most + Recent)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: m-langs.svg
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_details: percentage

      - name: Isometric Commit Calendar (half-year)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: m-isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
