name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/metrics.yml
      - README.md
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) OVERVIEW (header + repositórios)
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: header, repositories
          config_timezone: America/Sao_Paulo
          filename: metrics-overview.svg
          # Deixe o overview leve
          plugin_followup: no
          plugin_activity: no
          plugin_habits: no

      # 2) LINGUAGENS (tile minimalista)
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: metrics-langs.svg
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css, scss

      # 3) ISOCALENDAR (contribuições do ano, compacto)
      - name: Year activity (isocalendar)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PedroFerreiraBento
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          filename: metrics-year.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
